name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  easy_refresh: 3.4.0
  dio: 5.4.3+1
  drift: 2.19.1+1
  flutter_screenutil: 5.9.3
  file_picker: 8.0.7
  get: 4.6.6
  go_router: 14.2.3
  oktoast: 3.4.0
  path: 1.9.0
  path_provider: 2.1.3
  permission_handler: 11.3.1
  sqlite3_flutter_libs: 0.5.24
  url_launcher: 6.3.0
  log_wrapper:
    path: ../log_wrapper
  mvc:
    path: ../mvc
  network:
    path: ../network
  route:
    path: ../route
  extensions:
    path: ../extensions
  widgets:
    path: ../widgets

dependency_overrides:
  log_wrapper:
    path: ../log_wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  drift_dev: 2.19.1
  build_runner: 2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/